// DO NOT EDIT THIS FILE - IT IS GENERATED FROM routes.json
export default {
  "/": {
    title: "",
    import: import("../views/v-home/v-home.js"),
    component: "v-home",
    protected: false,
  },
  "/about": {
    title: "About",
    import: import("../views/v-about/v-about.js"),
    component: "v-about",
    protected: false,
  },
  "/signup": {
    title: "Sign Up",
    import: import("../views/v-signup/v-signup.js"),
    component: "v-signup",
  },
  "/login": {
    title: "Log In",
    import: import("../views/v-login/v-login.js"),
    component: "v-login",
  },
};
