// DO NOT EDIT THIS FILE - IT IS GENERATED FROM routes.json
export default {
  "/": {
    import: import("../views/v-home/v-home.js"),
    component: "v-home",
    protected: false,
  },
  "/about": {
    import: import("../views/v-about/v-about.js"),
    component: "v-about",
    protected: false,
  },
};
